@Day15_WebApi_HostAddress = https://localhost:7105

GET {{Day15_WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Day15_WebApi_HostAddress}}/api/todoitems
Content-Type: application/json

{
  "name": "walk dog",
  "isComplete": true
}

###

GET {{Day15_WebApi_HostAddress}}/api/todoitems

###

@id=1
GET {{Day15_WebApi_HostAddress}}/api/todoitems/{{id}}

###
